# Generated by Django 2.1.1 on 2018-11-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('cond', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=4)),
                ('produtos', models.TextField()),
                ('obs1', models.CharField(blank=True, max_length=80)),
                ('obs2', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
