# Generated by Django 2.1.1 on 2018-11-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedhist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='price_ok',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
