# Generated by Django 2.1.1 on 2018-09-25 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32)),
                ('business_name', models.CharField(max_length=150)),
                ('dba', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('address_1', models.CharField(blank=True, max_length=120)),
                ('address_2', models.CharField(blank=True, max_length=120)),
                ('address_3', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('zip_code', models.CharField(blank=True, max_length=18)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('contact', models.CharField(blank=True, max_length=80)),
                ('phone_main', models.CharField(blank=True, max_length=32)),
                ('phone_2', models.CharField(blank=True, max_length=32)),
                ('phone_3', models.CharField(blank=True, max_length=32)),
                ('email_main', models.EmailField(blank=True, max_length=255)),
                ('email_finance', models.EmailField(blank=True, max_length=255)),
                ('federal_id', models.CharField(blank=True, max_length=32)),
                ('state_id', models.CharField(blank=True, max_length=32)),
                ('city_id', models.CharField(blank=True, max_length=32)),
                ('shipping_address_1', models.CharField(blank=True, max_length=120)),
                ('shipping_address_2', models.CharField(blank=True, max_length=120)),
                ('shipping_address_3', models.CharField(blank=True, max_length=120)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=80)),
                ('shipping_zip_code', models.CharField(blank=True, max_length=18)),
                ('shipping_country', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
