# Generated by Django 2.1.1 on 2018-10-04 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aguardando', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aguardando',
            options={'ordering': ['estado', 'data', 'cliente']},
        ),
        migrations.AlterModelOptions(
            name='chegando',
            options={'ordering': ['container', 'produto']},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='aguardando',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
