# Generated by Django 2.1.1 on 2018-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aguardando', '0002_auto_20181004_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aguardando',
            name='obs',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
