# Generated by Django 2.1.1 on 2018-10-04 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aguardando', '0003_auto_20181004_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aguardando',
            options={'ordering': ['estado', 'data_hora']},
        ),
        migrations.RemoveField(
            model_name='aguardando',
            name='data',
        ),
        migrations.AddField(
            model_name='aguardando',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
