# Generated by Django 2.1.1 on 2018-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aguardando', '0005_auto_20181004_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aguardando',
            options={'ordering': ['container', 'produto', 'estado', 'data_hora']},
        ),
        migrations.AddField(
            model_name='aguardando',
            name='container',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
