# Generated by Django 2.1.1 on 2018-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aguardando', '0006_auto_20181004_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aguardando',
            options={'ordering': ['estado', 'container', 'produto', 'data_hora']},
        ),
    ]
