# Generated by Django 2.1.1 on 2018-11-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aguardando', '0007_auto_20181004_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chegando',
            options={'ordering': ['container', 'produto']},
        ),
    ]
